### ISSUE TITLE
[Quote]Need a start condition whit return NULL for nothing or return " or ' if one of these quote is needed to run.

### ISSUE THREAD

**Issue by zoun** [tblaudez/21sh---tmp-repo#23]
Besoin d'une condition avant le lancement de init_quote pour remplacer le is_quote actuel, il devra être du type
if (c = is_quote_start(shell->line->line_data) != NULL)
    init_quote(c, shell)

"c" qui vaudra soit NULL, si aucun quote a besoin detre lancer, " ou ' si un des deux doit être lancer.

**Comment by sgalasso42** [comment]
Easy
